# Generated by Django 5.2.3 on 2025-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
